import type { Metadata } from "next"
import { Inter, JetBrains_Mono } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { RootProvider } from "fumadocs-ui/provider/next"
import SearchDialog from "@/components/search-dialog"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
})

const interHead = Inter({
  subsets: ["latin"],
  variable: "--font-head",
  weight: ["700", "800", "900"],
  display: "swap",
})

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "500", "700"],
  display: "swap",
})

const SITE_URL = "https://www.jopgood.com"
const SITE_NAME = "Jopgood PWA"
const SITE_DESCRIPTION =
  "Headless, type-safe primitives for managing push notification subscriptions, service-worker lifecycle, and browser permissions."

export const metadata: Metadata = {
  // metadataBase resolves all relative URLs (icons, OG images) — without
  // this, Next warns on every build and link previews use broken paths.
  metadataBase: new URL(SITE_URL),

  // title.template auto-appends the site name to every page's title
  // (e.g. "Quick Start" becomes "Quick Start · Jopgood PWA").
  title: {
    default: SITE_NAME,
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "PWA",
    "push notifications",
    "service worker",
    "React",
    "headless",
    "TypeScript",
  ],
  authors: [{ name: "Jopgood" }],
  creator: "Jopgood",

  // Icons — SVG for modern browsers, PNG for iOS home-screen install.
  // Sources live in public/ (generated by scripts/generate-icons.mjs from
  // public/favicon.svg).
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },

  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    locale: "en_GB",
    // Default OG image is generated at build time by app/opengraph-image.tsx.
    // Next picks it up automatically; no explicit images entry needed here.
  },

  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },

  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },

  // Web app manifest wires PWA install (Add to Home Screen).
  // Generated at /manifest.webmanifest by app/manifest.ts.
  manifest: "/manifest.webmanifest",
}

export const viewport = {
  themeColor: "#c84b31", // brand terracotta
  colorScheme: "light",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${interHead.variable} ${jetbrainsMono.variable}`}
    >
      <body>
        <ThemeProvider>
          <RootProvider
            // Light-only for now; next-themes is also disabled by our
            // ThemeProvider passthrough above.
            theme={{ enabled: false }}
            search={{
              // Custom dialog using our own shadcn primitives. The hook
              // inside it points at /api/search (built by createFromSource
              // + staticGET, emitted as a static JSON asset by
              // `output: "export"`).
              SearchDialog,
            }}
          >
            {children}
          </RootProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
